project:
  type: website
  output-dir: docs

website:
  description: "Sitio web de la comunidad de usuarias y usuarios de R en Chile"
  site-url: https://ruserschile.github.io
  title: "R Chile"
  navbar:
    right:
      - text: Introducci√≥n
        href: introduccion.qmd
      - text: Blog
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/RusersChile
      - icon: twitter
        href: https://twitter.com/RusersChile
format:
  html:
    lang: "es"
    theme:
      - litera
      - brand
    css: styles.css



