project:
  type: website
  output-dir: docs

website:
  description: "Sitio web de la comunidad de usuarias y usuarios de R en Chile"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "R Chile"
  navbar:
    right:
      - text: Blog
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/RusersChile
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css



